name: Node.js Package

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm run build
      - run: npm publish
        if: ${{ !contains(github.ref, 'beta')}}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: npm run beta
        if: ${{ contains(github.ref, 'beta')}}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: curl https://npmmirror.com/sync/@serverless-devs/s
      - name: pkg
        run: npm run pkg
      - name: Rename files
        run: |
          mv releases/s-macos s-${{ github.ref_name }}-macos
          mv releases/s-linux s-${{ github.ref_name }}-linux
          mv releases/s-win.exe s-${{ github.ref_name }}-win.exe
      - name: Install ossutil
        run: curl https://gosspublic.alicdn.com/ossutil/install.sh | sudo bash
      - name: Upload file to OSS
        run: ossutil --endpoint ${{secrets.ENDPOINT}} --access-key-id ${{secrets.AK}} --access-key-secret ${{secrets.SK}} cp ./ oss://${{secrets.BUCKET_NAME}} -r --include "s-*" --only-current-dir
      - name: Zip files
        run: |
          zip -r s-${{ github.ref_name }}-macos.zip s-${{ github.ref_name }}-macos
          zip -r s-${{ github.ref_name }}-linux.zip s-${{ github.ref_name }}-linux
          zip -r s-${{ github.ref_name }}-win.exe.zip s-${{ github.ref_name }}-win.exe
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: |
            s-${{ github.ref_name }}-macos.zip
            s-${{ github.ref_name }}-linux.zip
            s-${{ github.ref_name }}-win.exe.zip
