name: Package

on: workflow_dispatch

jobs:
  publish-npm:
    if: github.repository == 'Serverless-Devs/Serverless-Devs'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - run: npm run build
      - name: pkg
        run: npm run pkg
      - name: Rename files
        run: |
          mv releases/s-macos s-v3.0.0-macos
          mv releases/s-linux s-v3.0.0-linux
          mv releases/s-win.exe s-v3.0.0-win.exe
      - name: Zip files
        run: |
          zip -r s-v3.0.0-macos.zip s-v3.0.0-macos
          zip -r s-v3.0.0-linux.zip s-v3.0.0-linux
          zip -r s-v3.0.0-win.exe.zip s-v3.0.0-win.exe
      - name: Install ossutil
        run: curl https://gosspublic.alicdn.com/ossutil/install.sh | sudo bash
      - name: Rename linux files
        run: mv s-v3.0.0-linux v3.0.0
      - name: Upload file to OSS
        run: ossutil --endpoint oss-cn-hangzhou.aliyuncs.com --access-key-id ${{secrets.AK}} --access-key-secret ${{secrets.SK}} cp v3.0.0 oss://serverless-tool-images/bin/s/