name: release-assets

on: 
  push:
    tags:
      - 'v*' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Install
        run: npm install
      - name: pkg
        run: npm run pkg
      - name: Zip the macos
        run: |
          zip -r ${{ github.ref_name }}.zip ./pkg/macos
      - name: Release
        uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: |
            ${{ github.ref_name }}.zip